### ISSUE TITLE
Add placenta and pancreas as organs

### ISSUE THREAD

**Issue by bhonick** [x-atlas-consortia/ubkg-neo4j#18]
Hi @AlanSimmons, please add `placenta` and `pancreas` as organs for the SenNet Data Sharing Portal!

Thanks!

(CC @JAH386)

**Comment by AlanSimmons** [comment]
# Dependency on refactoring of UBKG

Although the addition of new organs to the ontology source data is straightforward, it will likely not be available until at least the middle of the first week of August 2023.

I am currently [refactoring](https://github.com/x-atlas-consortia/ubkg-etl/issues/70) the UBKG. I will need to regression test some of the endpoints of the UBKG API.

**Comment by AlanSimmons** [comment]
Added to source (SimpleKnowledge spreadsheet).

**Comment by AlanSimmons** [comment]
Added to UBKG CSVs. Should be in Dev on Monday August 8.

**Comment by AlanSimmons** [comment]
Dependency on completion of https://github.com/x-atlas-consortia/hs-ontology-api/issues/14

**Comment by AlanSimmons** [comment]
# Results of unit testing

Local Development API querying local development neo4j.



![Image](https://github.com/x-atlas-consortia/ubkg-neo4j/assets/10928372/b7eb4e39-cd28-4491-ad61-c419749b2c7f)

**Comment by bhonick** [comment]
@AlanSimmons Thanks for your help here -- is there a pathway for getting this on PROD?

**Comment by AlanSimmons** [comment]
We completed testing in both local dev (unit) and DEV (system). We plan to promote to PROD soon.

@yuanzhou will be moving the neo4j to PROD, so I will let him provide ETA.

**Comment by bhonick** [comment]
@AlanSimmons Thank you very much for the clarification!
