### ISSUE TITLE
General use UBKG docker container

### ISSUE THREAD

**Issue by shirey** [x-atlas-consortia/ubkg-neo4j#2]
- usable for local or server deployment
  - stored in DockerHub
  - will automatically mount specified set of CSVs and load on startup
  - download container and start with a single "run.sh" with the following parameters:
    - neo4j_password (required) the password used to connect to the Neo4j database
    - neo4j_username (optional) the username used to connect to the Neo4j database, if excluded uses the username `neo4j` by default
    - csv_dir: (optional) the path to the directory containing the csv file, if excluded uses the current directory by default
    - ui_port: (optional) the port to expose the Neo4j Browser/UI on (defaults to the default neo4j port 7474)
    - neo4j_port: (optional) the port to expose the neo4j/bolt:// interface on (defaults to the default neo4j port 7687)

**Comment by AlanSimmons** [comment]
Completed for MacOS and Linux.
