### ISSUE TITLE
Add 10x Multiome to Available Data Types (HuBMAP + SenNet)

### ISSUE THREAD

**Issue by bhonick** [x-atlas-consortia/ubkg-neo4j#28]
@AlanSimmons 10x Multiome (https://www.10xgenomics.com/products/single-cell-multiome-atac-plus-gene-expression) should be added to the UBKG to populate the `data types` dropdown on dataset registration for both HuBMAP and SenNet.

**Comment by AlanSimmons** [comment]
I'll need the information indicated in [this document](https://docs.google.com/document/d/1hczwCzcTb3MePoQ0ay5gFivwYVDZ2kURs4ZxpOeL890/edit?usp=sharing).

**Comment by bhonick** [comment]
@AlanSimmons Here you are, thanks: https://docs.google.com/spreadsheets/d/1P0mG7n-VOdWJHP3b798YKACt6-5IQhhyUpqisCJosVU/edit?usp=sharing

**Comment by AlanSimmons** [comment]
# Details

Information added to source spreadsheets. The changes will appear in neo4j, and thus available to the API, in a subsequent release. 

## Dependencies
- [refactoring of UBKG API](https://github.com/x-atlas-consortia/hs-ontology-api/issues/14)
- [enhancement of UBKG API related to new neo4j architecture](https://github.com/x-atlas-consortia/ubkg-api/issues/69)



Codes are the same in both ontologies--i.e., if the code is 99999, there is both a HUBMAP:99999 and a SENNET:99999.

{SAB} refers to either HUBMAP or SenNet

## nodes

code|term|role|comment
--|--|--|--
C014000|10x Multiome {SAB} Assay |container
C014001|10x Multiome Measurement Assay| assay| cross-referenced to EFO:0030059; isa 10x Genomics Assay
C014002|10x Multiome Dataset|Dataset type|isa Multiome Dataset 
C014003|10x-multiome|Dataset Data Type|ingestion key
C014004|10x Multiome|Display Name|how it will display in Portal

## edges
subject|predicate|object
--|--|--
10x Multiome {SAB} Assay|has_measurement_assay|10x Multiome Measurement Assay
10x Multiome {SAB} Assay|has_dataset|10x Multiome Dataset
10x Multiome Dataset|has_display_name|10x Multiome
10x Multiome Dataset|has_dataset_data_type|10x-multiome
10x Multiome Dataset|contains|pii
10x Multiome Dataset|has_provider|HubMAP IEC

## note
"External provider" means "lab processed"--i.e., the TMC provides both raw and processed files. 
"IEC" means that IEC handles the pipelines.

**Comment by AlanSimmons** [comment]
Put on hold.

**Comment by AlanSimmons** [comment]
@bhonick Reactivated. ETA end of day 9/25.

**Comment by AlanSimmons** [comment]
For now, keeping this to SenNet.

**Comment by AlanSimmons** [comment]
# Result in local development

UBKG API datasets endpoint:

![Image](https://github.com/x-atlas-consortia/ubkg-neo4j/assets/10928372/181d625f-d2c0-4189-a9ea-099cccb2f035)

**Comment by AlanSimmons** [comment]
- Unit test successful.
- System integration test in DEV successful.

**Comment by AlanSimmons** [comment]
# Only in SenNet

@bhonick @shirey I have not added 10x to the HuBMAP application ontology. We agreed to wait until we had more information regarding both the "soft assay type" and multi-assay initiatives.

I will close this card. If necessary, we can either re-open this or open a new one specific to HuBMAP.

**Comment by bhonick** [comment]
Thanks @AlanSimmons, sounds good to me!
