### ISSUE TITLE
Add "bone marrow" as organ to SenNet

### ISSUE THREAD

**Issue by bhonick** [x-atlas-consortia/ubkg-neo4j#36]
Hi @AlanSimmons , a data provider has requested that "bone marrow" be added as an organ type in SenNet. It already exists as an organ in HuBMAP. Please update the SenNet side of UBKG accordingly. Thanks!

**Comment by AlanSimmons** [comment]
In local development instance. Excerpt of result of datasets endpoint in local environment:

 {
        "code": "C030045",
        "organ_cui": "C0005953",
        "organ_uberon": "UBERON:0002371",
        "rui_code": "BM",
        "sab": "HUBMAP",
        "term": "Bone Marrow"
    },
