### ISSUE TITLE
Add GeoMX to list of Data Types in HuBMAP

### ISSUE THREAD

**Issue by bhonick** [x-atlas-consortia/ubkg-neo4j#37]
Hi @AlanSimmons, to meet a data provider's needs, I would like to request that `GeoMX` be added as a Data Type in HuBMAP. Here is the necessary form filled out (my responses are on the second sheet): https://docs.google.com/spreadsheets/d/1IfUtvOc2peVc1R8CZc2LPgQPhJ3kJADnyJijISeUzGk/edit#gid=1152955054. Thanks!

**Comment by yuanzhou** [comment]
10/17/2023, the UBKG Neo4j (built from Oct 10th CSVs) released to PROD with this added GeoMX dataset type.

**Comment by bhonick** [comment]
Thanks!
