### ISSUE TITLE
Add heart, thymus, bone as organs in SenNet; lymphatic vessel in HUBMAP

### ISSUE THREAD

**Issue by bhonick** [x-atlas-consortia/ubkg-neo4j#45]
Hi @AlanSimmons, a data provider has requested that "heart" be added as an organ type in SenNet. It already exists as an organ in HuBMAP. Please update the SenNet side of UBKG accordingly. Thanks!

**Comment by AlanSimmons** [comment]
@bhonick Please provide a list of **all** organs that should be in SenNet. There is no need to do this piecemeal.

**Comment by AlanSimmons** [comment]
[This document](https://docs.google.com/spreadsheets/d/1MdLOUJMatvi-25aGnxkR3ji88yXkqYJu6HU8vFSyExg/edit?usp=sharing) contains the current set of organ sites for SenNet.

Based on this, the Organ hierarchy for SenNet needs:

- Heart
- Thymus
- Bone (for Skeletal)

**Comment by AlanSimmons** [comment]
Excerpts from UBKG API in **local** development environment, showing updates to UBKG for Heart, Thymus, and Bone in SenNet ontology.

UBERON:0001474 is just "bone element" or "bone organ".

```
{
        "code": "C030070",
        "organ_cui": "C0018787",
        "organ_uberon": "UBERON:0000948",
        "rui_code": "HT",
        "sab": "SENNET",
        "term": "Heart"
    },
{
        "code": "C030072",
        "organ_cui": "C0040113",
        "organ_uberon": "UBERON:0002370",
        "rui_code": "TH",
        "sab": "SENNET",
        "term": "Thymus"
    },
{
        "code": "C030102",
        "organ_cui": "C0262950",
        "organ_uberon": "UBERON:0001474",
        "rui_code": "BX",
        "sab": "SENNET",
        "term": "Bone"
    },
```

**Comment by AlanSimmons** [comment]
# ETA 1st week of January
The updates to the UBKG will be deployed after the Winter Recess.

**Comment by AlanSimmons** [comment]
# For HUBMAP: lymphatic vessel

UBERON:0001473

**Comment by AlanSimmons** [comment]
@bhonick in production now

**Comment by bhonick** [comment]
Thanks Alan!
